### ISSUE TITLE
New Project Configuration - 4CORE Electric Bicycles Program

### ISSUE THREAD

**Issue by FourCoreEbikes** [e-mission/nrel-openpath-deploy-configs#110]
### Shortened Name

4CORE Ebike Program

### Program or Study?

program

### Mode Studied

e-bike

### Autogenerate OPcodes?

true

### OPcode Subgroups

test, default

### Start Month

05/2024

### Program Admin Contact

Rebekah Huehnel, Clean Transportation Program Manager, rebekah@fourcore.org

### First Language

en

### Deployment Partner Name

Four Corners Office for Resource Efficiency (4CORE)

### Project Name

Community Access to Electric Bicycles Program

### Summary Line 1

4CORE works to promote the adoption of clean transportation through the support of the Colorado Energy Office by providing free eBikes for vulnerable sectors and increasing zero emission transportation across Southern Colorado. The Community Access to Electric Bicycles Grant Program will increase access to eBikes and eTrikes as a healthy, zero emission mode of transportation for older adults in an underserved community of Colorado.

### Summary Line 2

If you are a program Participant, this app can help you log your trips and compete against others to benefit our environment.

### Short Textual Description

As the state of Colorado looks towards alternative modes of transportation besides driving, 4CORE and the state would like to observe the use of an electric bicycle by older adults. This program will give 25 electric bicycles/tricycles to income-qualified older adults, many of which have physical and financial limitations.

### Why We Collect

4CORE and the CEO can use the program to understand how often older adults use an electric bicycle,the distance of their trips, and what they use it for (leisure, errands, etc.). This will help us understand the use-case of micro mobility in small, more rural towns in Colorado. It also gives insight to a micro-mobility transportation option for an older demographic - which will provide unique data and observations.

### Research Question

How effective are electric bicycles, as a form of micro-mobility transportation, in small, rural towns?

### Research Question

Are electric bicycles a solution to clean transportation for an older demographic?

### Research Question

What are the limitations as well as strong points of electric bicycle use for adults over the age of 55?

### Second Language

es

### Deployment Partner Name

Oficina de Cuatro Esquinas para la Eficiencia de los Recursos (4CORE)

### Project Name

Programa de Acceso Comunitario a Bicicletas Eléctricas

### Summary Line 1

4CORE trabaja para promover la adopción de transporte limpio a través del apoyo de la Oficina de Energía de Colorado al proporcionar bicicletas eléctricas gratuitas para sectores vulnerables y aumentar el transporte con cero emisiones en todo el sur de Colorado. El Programa de subvenciones para acceso comunitario a bicicletas eléctricas aumentará el acceso a eBikes y eTrikes como un modo de transporte saludable y sin emisiones para adultos mayores en una comunidad desatendida de Colorado.

### Summary Line 2

Si participa en el programa, esta aplicación puede ayudarle a registrar sus viajes y competir contra otros en beneficio de nuestro medio ambiente.

### Short Textual Description

Mientras el estado de Colorado busca modos de transporte alternativos además de conducir, a 4CORE y al estado les gustaría observar el uso de bicicletas eléctricas por parte de adultos mayores. Este programa entregará 25 bicicletas/triciclos eléctricos a adultos mayores con ingresos calificados, muchos de los cuales tienen limitaciones físicas y financieras.

### Why We Collect

4CORE y el CEO pueden utilizar el programa para comprender con qué frecuencia los adultos mayores usan una bicicleta eléctrica, la distancia de sus viajes y para qué la usan (ocio, recados, etc.). Esto nos ayudará a comprender el caso de uso de la micromovilidad en pueblos pequeños y más rurales de Colorado. También brinda información sobre una opción de transporte de micromovilidad para un grupo demográfico de mayor edad, que proporcionará datos y observaciones únicos.

### Research Question

¿Cuán efectivas son las bicicletas eléctricas, como forma de transporte de micromovilidad, en ciudades pequeñas y rurales?

### Research Question

¿Son las bicicletas eléctricas una solución para el transporte limpio para un grupo demográfico de mayor edad?

### Research Question

¿Cuáles son las limitaciones y los puntos fuertes de ¿Uso de bicicleta eléctrica para adultos mayores de 55 años?

### Use imperial units of measure

true

### Include test users in metrics?

true

### Send notifications at trip end?

false

### Use default demographic survey?

true

### Use default mode and purpose labels?

true

### Use default reminder schedule?

true

### Overview Users

true

### Overview Active Users

true

### Overview Trips

true

### Overview Signup Trends

true

### Overview Trips Trend

true

### Data UUIDs

true

### Data Trips

true

### Map Heatmap

true

### Map Bubble

true

### Map Trip Lines

false

### Push Send

false

### Options UUIDs

true

### Options Emails

true

### Admin Access Emails

jenny@fourcore.org, rebekah@fourcore.org, kathleen@fourcore.org

**Comment by Abby-Wheelis** [comment]
@FourCoreEbikes Do you want to know who is associated with each opCode? If so, we need to change "Autogenerate OpCodes?" to false. 

When true, the codes are generated on the join page like here: [https://open-access-openpath.nrel.gov/join/](https://open-access-openpath.nrel.gov/join/), they are random and typically only the users will know the code. 

When false, you will pass out the codes individually, which is what it sounded like you were looking to do.

**Comment by Abby-Wheelis** [comment]
data collection underway - [https://4core-ebike-openpath.nrel.gov/public/](https://4core-ebike-openpath.nrel.gov/public/)
