### ISSUE TITLE
New Project Configuration - UW Personalized Recommendation Systems Study

### ISSUE THREAD

**Issue by sebastianbarry** [e-mission/nrel-openpath-deploy-configs#70]
### Shortened Name

uw-prs

### Program or Study?

study

### Autogenerate OPcodes?

true

### OPcode Subgroups

test,default

### Start Month

02/2024

### Program Admin Contact

For questions about the study, please contact Congjing Zhang at the University of Washington (email: congjing@uw.edu).

### First Language

en

### Deployment Partner Name

University of Washington

### Project Name

UW Personalized Recommendation Systems Study

### Summary Line 1

UW is focused on using rewards to encourage commuters to switch to energy- efficient and environment-friendly transportation options, with the goal of enhancing air quality.

### Summary Line 2

This APP can help you record your trips, including time, locations, and travel purpose.

### Summary Line 3

In this study, it is providing users with personalized recommendations (e.g., restaurants and museums) to change people’s lifestyle.

### Short Textual Description

To make better personalized recommendation, the data collection is very important. The APP can prioritize data collection tasks and identify crucial time points for data collection with the help of incorporation of latest developments in adaptive sensing, uncertainty quantification, and predictive science. On the other hand, the better personalized recommendation the APP can offer, the better user engagement, that will ultimately translate into a long-term adaption of the APP by a wide range of users.

### Why We Collect

UW can use the information in the APP to create tool and methods to better collect data. Then UW can build data-driven personalized recommendation models for responsive, data-driven decision-making. The APP can change travel behavior improvement of transit and micromobility by reducing car dependency and encouraging walking, biking, and transit use.

### Research Question

Conducting travel behavior modeling to aid in making accurate travel demand prediction and personalized recommendation.

### Research Question

The impact of rewards on people’s willingness to change the transportation mode.

### Second Language

es

### Deployment Partner Name

Universidad de Washington

### Project Name

Estudio de sistemas de recomendación personalizados de la Universidad de Washington

### Summary Line 1

La Universidad de Washington se centra en el uso de recompensas para alentar a los viajeros a cambiar a opciones de transporte energéticamente eficientes y respetuosas con el medio ambiente, con el objetivo de mejorar la calidad del aire.

### Summary Line 2

Esta aplicación puede ayudarle a registrar sus viajes, incluida la hora, los lugares y el motivo del viaje.

### Summary Line 3

En este estudio, proporciona a los usuarios recomendaciones personalizadas (por ejemplo, restaurantes y museos) para cambiar el estilo de vida de las personas.

### Short Textual Description

Para hacer una recomendación mejor personalizada, la recopilación de datos es muy importante. La aplicación puede priorizar las tareas de recopilación de datos e identificar momentos cruciales para la recopilación de datos con la ayuda de la incorporación de los últimos avances en detección adaptativa, cuantificación de incertidumbre y ciencia predictiva. Por otro lado, cuanto mejor sea la recomendación personalizada que pueda ofrecer la aplicación, mayor será la participación del usuario, lo que en última instancia se traducirá en una adaptación a largo plazo de la aplicación por parte de una amplia gama de usuarios.

### Why We Collect

UW puede utilizar la información de la APLICACIÓN para crear herramientas y métodos para recopilar mejor datos. Luego, la Universidad de Washington puede crear modelos de recomendación personalizados basados en datos para una toma de decisiones responsiva y basada en datos. La aplicación puede cambiar el comportamiento de viaje, mejorar el transporte público y la micromovilidad al reducir la dependencia del automóvil y fomentar el uso de caminar, andar en bicicleta y el transporte público.

### Research Question

Realizar modelos de comportamiento de viaje para ayudar a realizar predicciones precisas de la demanda de viajes y recomendaciones personalizadas.

### Research Question

El impacto de las recompensas en la voluntad de las personas de cambiar el modo de transporte.

### Use imperial units of measure

true

### Include test users in metrics?

true

### Send notifications at trip end?

false

### Use default demographic survey?

true

### First Language

en - Answered

### Second Language

es - Contestada

### Use default mode and purpose labels?

true

### Use default reminder schedule?

true

### Overview Users

true

### Overview Active Users

true

### Overview Trips

true

### Overview Signup Trends

true

### Overview Trips Trend

true

### Data UUIDs

true

### Data Trips

true

### Data Trips Columns Exclude

data.start_loc.coordinates, data.end_loc.coordinates

### Map Heatmap

true

### Map Bubble

true

### Map Trip Lines

false

### Push Send

false

### Options UUIDs

true

### Options Emails

true

### Admin Access Emails

congjing@uw.edu, ryanflin@uw.edu, ugurel@uw.edu

**Comment by Abby-Wheelis** [comment]
testing/collection in progress - [https://uw-prs-openpath.nrel.gov/public/](https://uw-prs-openpath.nrel.gov/public/)
