### ISSUE TITLE
New Project Configuration - Ride 2 Own E-Bike Pilot Program: Milwaukie

### ISSUE THREAD

**Issue by tstmadi** [e-mission/nrel-openpath-deploy-configs#82]
### Shortened Name

r2omilwaukie

### Program or Study?

program

### Mode Studied

e-bike

### Autogenerate OPcodes?

true

### OPcode Subgroups

test, default

### Start Month

5/2024

### Program Admin Contact

Madi Carlson (madi@thestreettrust.org), Burgin Utaski (burgin@thestreettrust.org)

### First Language

en

### Deployment Partner Name

The Street Trust

### Project Name

Ride 2 Own E-Bike Pilot Program: Milwaukie

### Summary Line 1

The Street Trust aims to remove (offset) barriers to entry for e-bike ownership, contributing to the health and wellbeing of participants by using an energy-efficient, non-polluting mode of transportation that maximizes air quality benefits.

### Summary Line 2

This pilot program provides e-bikes to individuals in Milwaukie, OR who want to start riding, but don't have the financial means or previous experience to purchase one themselves.

### Summary Line 3

If you are a program participant, this app can help you log your trips.

### Short Textual Description

TST would like to pilot the demand-shift potential for e-bike ownership in the Portland area by hosting a year-long "ride to own" program where participants receive a free e-bike, gear, accessories, and bike education in exchange for one year of qualitative and quantitative trip data sharing. To gather the data needed, this pilot requires an automated trip tracking solution for understanding travel behavior. The pilot will allow TST to understand variations in travel across days of the week and months of the year without complex, time-consuming surveys.

### Why We Collect

The data collected during the program will be used to understand how e-bikes are used, including when and how often as well as distance traveled. TST can use this information to understand how people are using e-bikes, what their constraints are, and will help policymakers and decisionmakers in Oregon understand how to better provide bike infrastructure to the area. This comprehensive information will aid TST in its mission to help build a complete, safe, low-carbon, multimodal transportation system that contributes to equity in access, opportunity, health, and prosperity for people and communities across the Portland Metro Region and beyond.

### Research Question

Travel behavior modeling to support cost-benefit analyses of other ride-to-own e-bike programs as well as e-bike ownership for low-income individuals.

### Research Question

Travel behavior modeling to inform local and regional bike infrastructure investments.

### Research Question

The impact of demand shifts towards e-bike use on transportation energy efficiency and GHG emissions.

### Second Language

None

### Use imperial units of measure

true

### Include test users in metrics?

true

### Send notifications at trip end?

false

### Use default demographic survey?

true

### First Language

EN

### Second Language

ES

### Use default mode and purpose labels?

true

### Use default reminder schedule?

true

### Overview Users

true

### Overview Active Users

true

### Overview Trips

true

### Overview Signup Trends

true

### Overview Trips Trend

true

### Data UUIDs

true

### Data Trips

true

### Map Heatmap

true

### Map Bubble

true

### Map Trip Lines

false

### Push Send

false

### Options UUIDs

true

### Options Emails

true

### Admin Access Emails

madi@thestreettrust.org, burgin@thestreettrust.org, volunteer@thestreettrust.org

**Comment by Abby-Wheelis** [comment]
In progress now - [https://r2omilwaukie-openpath.nrel.gov/public/](https://r2omilwaukie-openpath.nrel.gov/public/)
