### ISSUE TITLE
New Project Configuration - godcgo

### ISSUE THREAD

**Issue by shankari** [e-mission/nrel-openpath-deploy-configs#98]
### Shortened Name

godcgo

### Program or Study?

program

### Mode Studied

bike

### Autogenerate OPcodes?

true

### Start Month

05/2024

### Program Admin Contact

Samantha Huff at goDCgo (samantha.huff@godcgo.com)

### First Language

en

### Deployment Partner Name

goDCgo

### Project Name

goDCgo

### Summary Line 1

goDCgo aims to decrease car usage and traffic by promoting sustainable and affordable options to get around this District.

### Summary Line 2

goDCgo provides complimentary transit resources and services to DC organizations and commuters.

### Summary Line 3

If you are a campaign participant, this app can help you track your sustainability metrics and provide valuable information to goDCg on how sustainable transportation is being used.

### Short Textual Description

goDCgo is an initiative with the District Department of Transportation, that promotes the use of sustainable transportation. With the aim to decrease car usage and traffic with sustainable, affordable ways of getting around, goDCgo would like to experiment with an automated ("passive") trip tracking solution for understanding travel behavior. This program study can allow goDCgo and its partner NREL to understand mode shifts and transportation patterns without complex, time-consuming surveys.

### Why We Collect

The data collected during goDCgo's ongoing campaigns will be used to understand how sustainable transportation is being used by DC residents, including when and how, as well as distance traveled. It will help goDCgo understand VMT and carbon reductions as a result of recipients' subsituted travel.

### Research Question

How much VMT is reduced from campaign participants traveling by biking, walking, scooting, or taking public transit instead of driving?

### Research Question

What is the number, frequency, and duration of rides from campaign participants?

### Research Question

How do campaign travel patterns differ by demographics and/or location?

### Second Language

None

### Use imperial units of measure

true

### Include test users in metrics?

true

### Send notifications at trip end?

false

### Use default demographic survey?

true

### Use default mode and purpose labels?

true

### Use default reminder schedule?

true

### Overview Users

true

### Overview Active Users

true

### Overview Trips

true

### Overview Signup Trends

true

### Overview Trips Trend

true

### Data UUIDs

true

### Data Trips

true

### Map Heatmap

true

### Map Bubble

true

### Map Trip Lines

false

### Push Send

false

### Options UUIDs

true

### Options Emails

true

### Admin Access Emails

samantha.huff@godcgo.com,
kathryn.lang@dc.gov

**Comment by Abby-Wheelis** [comment]
data collection underway - [https://godcgo-openpath.nrel.gov/public/](https://godcgo-openpath.nrel.gov/public/)
